# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: aquaponicCowboy dot com 
email: brian@apcowboy.com 
description: >- # this means to ignore newlines until "baseurl:"
  The metaphor of the blind men describing an elephant is a classic tale that originated from the Indian subcontinent. It has been used in various religious traditions and philosophies to illustrate the nature of truth, reality, and human perception. The story goes like this:

A group of blind men encounters an elephant for the first time. Each man touches a different part of the elephant, such as the trunk, tusk, ear, leg, or tail. Based on their limited individual experiences, they try to describe what an elephant is like.

The man who touches the trunk says that an elephant is like a snake. The one who touches the tusk believes it is like a spear. The man who touches the ear describes it as a fan, while the one who touches the leg thinks it is like a tree trunk. The man who touches the tail concludes that an elephant is like a rope.

Each blind man is convinced that their perspective is correct and that the others are wrong. This leads to disagreement and conflict among them. However, they are all partially correct, as they each experienced a different aspect of the same elephant. The complete truth about the elephant can only be understood by combining their perspectives.

The metaphor of the blind men and the elephant serves as a reminder that our individual perceptions and experiences can lead to incomplete or distorted understandings of reality. It encourages us to be open to diverse perspectives and to seek a more comprehensive understanding of the truth.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aquaponiccowboy 
github_username:  aquaponiccowboy

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
